FROM node:24-alpine AS base

WORKDIR /usr/src/www

ARG URL
ENV PUBLIC_URL=$URL

COPY package*.json ./
RUN npm install

FROM base AS build
COPY src/ ./src/
COPY public/ ./public/
COPY static/astro.config.mjs ./
COPY tsconfig.json ./
RUN npm run build

FROM caddy:2.11.4-alpine AS serve
COPY --from=build /usr/src/www/dist /var/www
COPY static/Caddyfile /etc/caddy/Caddyfile
